# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalCashService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='digitalCashService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x64igitalCashService.proto\"M\n\x07Message\x12\x13\n\x0bmessageData\x18\x01 \x01(\t\x12\x1b\n\x13numberOfMoneyOrders\x18\x02 \x01(\x05\x12\x10\n\x08MOString\x18\x03 \x01(\t\"\'\n\x03\x61\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0bpingMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xec\x01\n\x12\x64igitalCashService\x12,\n\x16sendToBankFromCustomer\x12\x08.Message\x1a\x08.Message\x12,\n\x1asendToMerchantFromCustomer\x12\x08.Message\x1a\x04.ack\x12,\n\x16sendToBankFromMerchant\x12\x08.Message\x1a\x08.Message\x12\x30\n\x1asendToCustomerFromMerchant\x12\x08.Message\x1a\x08.Message\x12\x1a\n\x04ping\x12\x0c.pingMessage\x1a\x04.ackb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageData', full_name='Message.messageData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberOfMoneyOrders', full_name='Message.numberOfMoneyOrders', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MOString', full_name='Message.MOString', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=105,
)


_ACK = _descriptor.Descriptor(
  name='ack',
  full_name='ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ack.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ack.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=146,
)


_PINGMESSAGE = _descriptor.Descriptor(
  name='pingMessage',
  full_name='pingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pingMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ack'] = _ACK
DESCRIPTOR.message_types_by_name['pingMessage'] = _PINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'digitalCashService_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'digitalCashService_pb2'
  # @@protoc_insertion_point(class_scope:ack)
  ))
_sym_db.RegisterMessage(ack)

pingMessage = _reflection.GeneratedProtocolMessageType('pingMessage', (_message.Message,), dict(
  DESCRIPTOR = _PINGMESSAGE,
  __module__ = 'digitalCashService_pb2'
  # @@protoc_insertion_point(class_scope:pingMessage)
  ))
_sym_db.RegisterMessage(pingMessage)



_DIGITALCASHSERVICE = _descriptor.ServiceDescriptor(
  name='digitalCashService',
  full_name='digitalCashService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=181,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendToBankFromCustomer',
    full_name='digitalCashService.sendToBankFromCustomer',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendToMerchantFromCustomer',
    full_name='digitalCashService.sendToMerchantFromCustomer',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendToBankFromMerchant',
    full_name='digitalCashService.sendToBankFromMerchant',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendToCustomerFromMerchant',
    full_name='digitalCashService.sendToCustomerFromMerchant',
    index=3,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='digitalCashService.ping',
    index=4,
    containing_service=None,
    input_type=_PINGMESSAGE,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGITALCASHSERVICE)

DESCRIPTOR.services_by_name['digitalCashService'] = _DIGITALCASHSERVICE

# @@protoc_insertion_point(module_scope)
